### ISSUE TITLE
HU03 - Consultar el listado de artistas

### ISSUE THREAD

**Issue by JSVargasQ** [jhalep-miso/VinilosApp#5]
**Descripción**

**Como** usuario visitante, **deseo** ver el listado de artistas **para** seleccionar aquellos que más me interesen.
## Criterios de Aceptación
- Al seleccionar la opción de artistas, se debe visualizar un listado navegable con los artistas disponibles
- Se debe visualizar por cada elemento de la lista de artistas la siguiente información:
	- Fotografía
	- Nombre
	- Descripción
	- Fecha de creación
	- Cantidad de álbumes
	- Cantidad de premios
- Todos los elementos de la lista deben mantener las mismas dimensiones, los textos de descripción pueden truncarse para mantener esta característica
- En caso de no contar con una fotografía, se debe mostrar una imagen por defecto
- En caso de haber un error al cargar la lista de directores debe informarse al usuario

## Prototipo

![Image](https://github.com/user-attachments/assets/37c40766-f3e0-4295-8386-99920ee65f90)

***
## Tareas
- [x] [Construcción de interfaz gráfica](https://github.com/jhalep-miso/VinilosApp/issues/11)
- [x] [Conexión con servicios REST](https://github.com/jhalep-miso/VinilosApp/issues/12)
- [x] [Pruebas unitarias](https://github.com/jhalep-miso/VinilosApp/issues/13)
- [x] [Pruebas funcionales y/o extremo a extremo](https://github.com/jhalep-miso/VinilosApp/issues/14)
- [x] [Documentación](https://github.com/jhalep-miso/VinilosApp/issues/15)
