### ISSUE TITLE
HU04 - Consultar la información detallada de un artista

### ISSUE THREAD

**Issue by JSVargasQ** [jhalep-miso/VinilosApp#6]
**Descripción**
**Como** usuario visitante, **quiero** ver la información detallada de un artista específico **para** ampliar mis conocimientos sobre él.

### Criterios de aceptación
Al ingresar al detalle de un artista, debe mostrarse la siguiente información
- Fotografía
- Descripción completa
- Fecha de creación
- Listado de músicos que componen al grupo del artista (solo si están disponibles), donde para cada uno se muestra
	- fotografía
	- Nombre
	- Fecha de nacimiento
- Listado de álbumes del artista, donde para cada album se muestra
	- Cover
	- Título
	- Descripción
	- Sello discográfico
	- Género
- Al seleccionar uno de los álbumes, debe llevar al usuario a la visualización del detalle del álbum 
- Todos los elementos de la lista de álbumes deben mantener las mismas dimensiones, los textos de descripción pueden truncarse para mantener esta característica
- En caso de no contar con fotografías, se debe mostrar una imagen por defecto
- En caso de haber un error al cargar los datos debe informarse al usuario

### Prototipo
![Image](https://github.com/user-attachments/assets/2aa364d6-5efc-46f4-ab53-f19b7f8283ed)

### Tareas
- [ ] [Construcción de interfaz gráfica](https://github.com/jhalep-miso/VinilosApp/issues/16)
- [ ] [Conexión con servicios REST](https://github.com/jhalep-miso/VinilosApp/issues/17)
- [ ] [Pruebas unitarias](https://github.com/jhalep-miso/VinilosApp/issues/18)
- [ ] [Pruebas funcionales y/o extremo a extremo](https://github.com/jhalep-miso/VinilosApp/issues/19)
- [ ] [Documentación](https://github.com/jhalep-miso/VinilosApp/issues/20)
