### ISSUE TITLE
HU05 - Consultar listado de coleccionistas

### ISSUE THREAD

**Issue by JSVargasQ** [jhalep-miso/VinilosApp#7]
**Descripción**
**Como** usuario visitante, **deseo** consultar el listado de coleccionistas **para** seleccionar aquel que más me interese.

## Criterios de aceptación
- Al seleccionar la opción de Coleccionistas, se debe visualizar un listado de los coleccionistas disponibles en la aplicación.
- Cada ítem del listado debe mostrar una imagen alusiva al coleccionista y el nombre del mismo. Si no cuenta con una imagen disponible se tendrá que mostrar una por defecto.
- Todos los ítems de la lista deben mantener las mismas dimensiones y formato de texto.
- Si existe un error al traer la información del backend, se tendrá que mostrar un error amigable al usuario.

## Prototipo
![image](https://github.com/user-attachments/assets/b7f16f9d-7f6e-42fd-8591-d808dc9ce5c0)

***
## Tareas
- [ ] [Construcción de interfaz gráfica](https://github.com/jhalep-miso/VinilosApp/issues/31)
- [ ] [Conexión con servicios REST](https://github.com/jhalep-miso/VinilosApp/issues/32)
- [ ] [Pruebas unitarias](https://github.com/jhalep-miso/VinilosApp/issues/33)
- [ ] [Pruebas funcionales y/o extremo a extremo](https://github.com/jhalep-miso/VinilosApp/issues/34)
- [ ] [Documentación](https://github.com/jhalep-miso/VinilosApp/issues/35)
