### ISSUE TITLE
HU06 - Consultar la información detallada de un coleccionista

### ISSUE THREAD

**Issue by JSVargasQ** [jhalep-miso/VinilosApp#8]
**Descripción**
**Como** usuario visitante, **quiero** ver la información detallada de un coleccionista específico **para** conocer sus gustos musicales.

## Criterios de aceptación
- Al seleccionar un Coleccionista en específico se debe desplegar la vista de detalle del mismo.
- En la vista de detalle se tiene que ver el Nombre, Número celular y Correo electrónico.
- Se debe ver un listado de los Álbumes coleccionados por este.
- La lista de álbumes debe mostrar la Imagen del Álbum, Nombre del Álbum, Descripción y Género.
- La lista de álbumes debe mantener las mismas dimensiones en cada ítem.

 
## Prototipo
![image](https://github.com/user-attachments/assets/2759ca36-46b8-4bf2-b120-86a4d78192da)

***
## Tareas
- [ ] [Construcción de interfaz gráfica](https://github.com/jhalep-miso/VinilosApp/issues/36)
- [ ] [Conexión con servicios REST](https://github.com/jhalep-miso/VinilosApp/issues/37)
- [ ] [Pruebas unitarias](https://github.com/jhalep-miso/VinilosApp/issues/38)
- [ ] [Pruebas funcionales y/o extremo a extremo](https://github.com/jhalep-miso/VinilosApp/issues/39)
- [ ] [Documentación](https://github.com/jhalep-miso/VinilosApp/issues/40)
